# Generated by Django 2.2.16 on 2022-07-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220726_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User role',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='user', max_length=8, verbose_name='User role'),
        ),
    ]
