# Generated by Django 2.2.16 on 2022-07-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220726_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(help_text='Добавьте адрес категории', unique=True, verbose_name='Уникальный адрес категории'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(help_text='Добавьте адрес жанра', unique=True, verbose_name='Уникальный адрес жанра'),
        ),
    ]
